# Generated by Django 5.1.7 on 2025-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_options_genre_active_genre_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
