# Generated by Django 5.1.7 on 2025-03-11 19:27

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Nacionalidade'),
        ),
    ]
