# Generated by Django 5.1.7 on 2025-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='resume',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
